#!/bin/bash

binaries=$(echo "client server" | tr " " "\n")
selected=`echo "$binaries" | fzf`

cargo build --release --bin $selected
if [ $selected == "client" ]; then
	read -p "id: " id
	RUST_LOG=debug ./target/release/$selected set-id $id
else
	RUST_LOG=debug ./target/release/$selected
fi
